version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:80" # Map host port 5173 to container port 80
    volumes:
      - ./frontend/src:/app/src # Mount source code for live-reloading (optional, for development)
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - "3000:3000" # Map host port 3000 to container port 3000
    volumes:
      - ./backend:/app # Mount source code for live-reloading (optional, for development)
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - PORT=3000